server:
  port: 8080

spring:
  application:
    name: ms-housepass-user
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: 1234
      database: db-user
      port: 27017
      host: localhost      
  config:
    import: optional:configserver:
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
